windowrule {
	name = btop
	match:class = btop-persist
	workspace = special:btop
	float = true
	size = monitor_w*0.66 monitor_h*0.9
	center = true
}

# windowrule {
# 	name = vesktop
# 	match:class = vesktop
# 	workspace = special:vesktop
# 	float = true
# 	size = monitor_w*0.66 monitor_h*0.9
# 	center = true
# }

# windowrulev2 = float, class:org.pulseaudio.pavucontrol
# windowrulev2 = size 2000 800, class:org.pulseaudio.pavucontrol

#
# windowrulev2 = match class:vesktop, workspace special:vesktop silent
# windowrulev2 = float, class:vesktop
# windowrulev2 = size 60% 90%, class:vesktop
# windowrulev2 = center, class:vesktop

#teams
# windowrulev2 = workspace special:teams silent, class:'Microsoft Teams - Preview'
# windowrulev2 = float, class:'Microsoft Teams - Preview'
# windowrulev2 = size 60% 90%, class:'Microsoft Teams - Preview'
# windowrulev2 = center, class:'Microsoft Teams - Preview'
