vim.g.mapleader = ' '
vim.keymap.set('n', '<c-<Left>>', '<c-w>h')
vim.keymap.set('n', '<c-<Right>>', '<c-w>l')
vim.keymap.set('n', '<leader>/', ':noh<CR>')
vim.keymap.set('n', '<leader>t', ':NvimTreeOpen<CR>')
vim.keymap.set('n', '<leader>l', ':bnext<CR>')
vim.keymap.set('n', '<leader>h', ':bprev<CR>')
vim.keymap.set('n', '<c-u>', ':call smooth_scroll#up(&scroll, 8, 2)<CR>', {silent = true })
vim.keymap.set('n', '<c-d>', ':call smooth_scroll#down(&scroll, 8, 2)<CR>', {silent = true })
vim.keymap.set('n', '<c-b>', ':call smooth_scroll#up(&scroll*2, 8, 4)<CR>', {silent = true })
vim.keymap.set('n', '<c-f>', ':call smooth_scroll#down(&scroll*2, 8, 4)<CR>', {silent = true })
vim.keymap.set('n', '<leader>b', ':CtrlPBuffer<CR>')

-- DAP Keybinds
vim.keymap.set('n', '<F5>', function() require('dap').continue() end, {silent = true})
vim.keymap.set('n', '<leader>dh', function() require('dap.ui.widgets').hover() end, {silent = true})
vim.keymap.set('n', '<F9>', function() require('dap').toggle_breakpoint() end, {silent = true})
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, {silent = true})
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, {silent = true})
vim.keymap.set('n', '<leader>dr', function() require('dap').repl.open() end, {silent = true})
